
version: "3.8"

services:

  nats-streaming:
      container_name: nats-streaming
      image: nats-streaming:linux
      ports:
        - "8222:8222"
        - "4222:4222"

  postgresql:
    container_name: postgres
    build:
      context: ./postgres/
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgresql
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wb-L0:
    container_name: wb-L0
    depends_on:
      - postgresql
      - nats-streaming
    build:
      context: ./
    image: wbl0
    restart: always
    ports:
      - "8080:${WBL0_PORT}"

volumes:
  db-data:
    name: db-data