bind_addr = ":8080"
log_level = "debug"
requestfreq = 500
sendmessagetimeout = 2500
[storage]
    host = "postgresql"
    port = "5432"
    database = "test"
    username = "deedsbaron"
    password = "0809"
    attempts2con = 5
[nats]
    serverID = "test-cluster"
    clientID = "test-wb-L0"
    natsUrl = "nats://nats-streaming:4222"
    interval = 1
    maxout = 5